### PR TITLE
Fixes for Chromecast volume

### PR DESCRIPTION
**Pull request by balloob**
It was line 119 from cast.py that was driving me crazy

### CODE REVIEW

**Comment by wind-rider** [comment]
It works well, when I adjust the volume in Home Assistant, the player app on my phone shows the new volume setting instantaneously and vice-versa, too!

The placement of the slider under the buttons is better, too.

The only thing I'm wondering about is why the buttons are orange and the slider is blue? Has google given any suggestions on that with UI guidelines?

**Comment by balloob** [comment]
Oh you're right, it should probably be orange too. Same for more light brightness.

We might even go ahead and replace the word volume with the volume icon, like in the [design guidelines](https://www.google.com/design/spec/components/sliders.html#sliders-continuous-slider). Even have a tap on volume icon trigger mute ?

**Comment by wind-rider** [comment]
About color - I think orange is the accent color of Home Assistant. This color is meant to make one action element stand out, to pull attention to. See https://www.google.com/design/spec/style/color.html#color-ui-color-application.
I'm not sure it is a good idea to use the accent color for multiple elements in the same dialog. What do you think?

Muting when the user taps the volume icon is cool, I already added the required method to the Mediaplayer class in python (also to the cast mediaplayer component).

The only pity is that unmuting (restoring the volume from before muting) currently won't work, because pychromecast didn't expose a method to do that. The way I implemented it now is just setting the volume to zero.

Of course the previous volume could be stored in Home Assistant but that won't work cross-browser. It would be better if that could be handled on the Chromecast itself.

**Comment by balloob** [comment]
You're right about the accent color. We should probably model it after Google Music, those people had a lot of time to figure out a proper design.

screen shot 2015-05-31 at 12 13 24

I was thinking about upgrading the base Media Player class today to improve sharing of certain logic. Thinks like the restoring volume after unmute are things that could be integrated there.

**Comment by wind-rider** [comment]
That restoring volume - I don't know whether the old volume is already stored on the chromecast device itself, but if we can use a native chromecast / other device method then you can e.g. mute from Home Assistant and unmute from another controller without depending on Home Assistant to have the old value.

I know there is a property "volume_muted" in the Chromecast mediastatus dictionary, but I don't know the inner workings of that. Do you know about that and whether it can be controlled?

**Comment by wind-rider** [comment]
I'm trying to convert the word "Volume" into a button now.

**Comment by balloob** [comment]
Ah yes, that is a good point about muting. SInce it is exposed via the cast status I expect it to be a command. Let's see if I can capture it

**Comment by wind-rider** [comment]
Have you already looked into https://github.com/googlecast/cast-volume-controller-polymer/ and https://github.com/googlecast/cast-player-bar-polymer?

**Comment by balloob** [comment]
Sadly, we can't use those custom elements. They are using the Cast JavaScript SDK, we're communicating with the Home Assistant media player api.

balloob/pychromecast@83aa115ab4e538c5bb96d96650c282e202ede331 :smile:

**Comment by wind-rider** [comment]
We can still look for inspiration at their design ;)

And cool that you found that Chromecast command :D I almost finished the button in the more info card

**Comment by wind-rider** [comment]
I'm ready to commit my work, can you then publish that updated pychromecast version to pypi? Otherwise people will have problems if they click on the mute button.

**Comment by balloob** [comment]
Done!

**Pull request merged**
